Update dry-types gem (#132)
* Update dry-types gem

Because we got a conflict in Shinobi when trying to install the fast-mcp gem

* Update Ruby to 3.3

* Remove CodeCov because we can't use it anymore

Here's the error we got today in the CI:
  _____          _
 / ____|        | |
| |     ___   __| | ___  ___ _____   __
| |    / _ \ / _\`|/ _ \/ __/ _ \ \ / /
| |___| (_) | (_| |  __/ (_| (_) \ V /
 \_____\___/ \__,_|\___|\___\___/ \_/
                               Ruby-0.6.0
==> GitHub Actions detected
x> No token specified or token is empty
==> Gzipping contents
==> Uploading reports
    url:   https://codecov.io
    query: token=secret&flags&package=ruby-0.6.0&service=github-actions&branch=update-dry-types&pr=132&slug=STUDITEMPS%2Futils&build=15630936590&commit=a9c34b50b89cb4ef33af2c943370175d07a8f2c2
->  Pinging Codecov
https://codecov.io/upload/v4?token=secret&flags&package=ruby-0.6.0&service=github-actions&branch=update-dry-types&pr=132&slug=STUDITEMPS%2Futils&build=15630936590&commit=a9c34b50b89cb4ef33af2c943370175d07a8f2c2
{"message":"Rate limit reached. Please upload with the Codecov repository upload token to resolve issue. Expected time to availability: 1447s."}
/home/runner/work/utils/utils/vendor/bundle/ruby/3.3.0/gems/codecov-0.6.0/lib/codecov/uploader.rb:56:in `upload': Could not upload reports to Codecov (StandardError)
	from /home/runner/work/utils/utils/vendor/bundle/ruby/3.3.0/gems/codecov-0.6.0/lib/codecov.rb:15:in `format'
	from /home/runner/work/utils/utils/vendor/bundle/ruby/3.3.0/gems/simplecov-0.21.2/lib/simplecov/result.rb:51:in `format!'
	from /home/runner/work/utils/utils/vendor/bundle/ruby/3.3.0/gems/simplecov-0.21.2/lib/simplecov/configuration.rb:197:in `block in at_exit'
	from /home/runner/work/utils/utils/vendor/bundle/ruby/3.3.0/gems/simplecov-0.21.2/lib/simplecov.rb:189:in `run_exit_tasks!'
	from /home/runner/work/utils/utils/vendor/bundle/ruby/3.3.0/gems/simplecov-0.21.2/lib/simplecov.rb:179:in `at_exit_behavior'
	from /home/runner/work/utils/utils/vendor/bundle/ruby/3.3.0/gems/simplecov-0.21.2/lib/simplecov/defaults.rb:30:in `block in <top (required)>'

Error: Process completed with exit code 1.